export const ACHIEVEMENTS = [
  {
    id: 'first_step',
    title: 'First Step',
    description: 'Complete your first pomodoro',
    icon: '👣',
    condition: { type: 'totalPomodoros', value: 1 },
  },
  {
    id: 'explorer',
    title: 'Explorer',
    description: 'Discover 5 zones on the map',
    icon: '🗺️',
    condition: { type: 'zonesDiscovered', value: 5 },
  },
  {
    id: 'architect',
    title: 'Architect',
    description: 'Contribute to fully restoring a zone',
    icon: '🏗️',
    condition: { type: 'zonesRestored', value: 1 },
  },
  {
    id: 'social_builder',
    title: 'Social Builder',
    description: 'Complete 10 co-op focus sessions',
    icon: '🤝',
    condition: { type: 'coopSessions', value: 10 },
  },
  {
    id: 'unstoppable',
    title: 'Unstoppable',
    description: 'Reach a 30-day streak',
    icon: '🔥',
    condition: { type: 'streak', value: 30 },
  },
  {
    id: 'night_owl',
    title: 'Night Owl',
    description: 'Complete 5 sessions after midnight',
    icon: '🦉',
    condition: { type: 'nightSessions', value: 5 },
  },
  {
    id: 'early_bird',
    title: 'Early Bird',
    description: 'Complete 5 sessions before 7am',
    icon: '🌅',
    condition: { type: 'morningSessions', value: 5 },
  },
  {
    id: 'centurion',
    title: 'Centurion',
    description: 'Complete 100 pomodoros',
    icon: '💯',
    condition: { type: 'totalPomodoros', value: 100 },
  },
  {
    id: 'deep_work',
    title: 'Deep Work',
    description: 'Complete a 50-minute session',
    icon: '🧠',
    condition: { type: 'longSession', value: 50 },
  },
  {
    id: 'shield_bearer',
    title: 'Shield Bearer',
    description: 'Earn your first streak shield',
    icon: '🛡️',
    condition: { type: 'shields', value: 1 },
  },
];
